### ISSUE TITLE
Upgrade to Hunspell 7.0

### ISSUE THREAD

**Issue by Jiminy68** [superbob/SublimeTextLanguageFrench#3]
Hi SuperBob,

First of all  thank you for this nice Fr dictionnary packaged for SublimeText.

Any plan to upgrade the Hunspell v5.1 dictionnary from 2014 to version 7.0 that has been  out since december 2020 ?

http://grammalecte.net/download/fr/hunspell-french-dictionaries-v7.0.zip

Thanks.

**Comment by superbob** [comment]
I just pushed this version https://github.com/superbob/SublimeTextLanguageFrench/releases/tag/0.2.3 containing updated dictionnaries. It should be available in Package Control soon.

**Comment by superbob** [comment]
The version is available in Package Control now. I close the issue.
